name: "Terraform Apply"

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "pmqs-cloud"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"
  CONFIG_DIRECTORY: "./"

jobs:
  calculate-directories:
    runs-on: ubuntu-latest
    outputs:
      directory_matrix: ${{ tosteps.calculate_directories.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Calculate directories to run plans for"
        id: calculate_directories
        working-directory: infrastructure/environments
        run: |
          JSON_OUTPUT=$(find . -type d -mindepth 2 -maxdepth 2 -not -path '*/terraform_cloud*' -not -path '*/gcp/foundation' -not -path '*/gcp/modules' | jq --raw-input --slurp 'split("\n") | del(..|select(. == ""))')
          echo "directories=$JSON_OUTPUT" >> "$GITHUB_OUTPUT"
  calculate-necessary-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: calculate-directories
    permissions:
      contents: read
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.calculate-directories.outputs.directory_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Calculate Workspace Name
        id: calculate-workspace-name
        working-directory: "infrastructure/environments/${{ matrix.directory }}"
        run: |
          terraform init
          echo "workspace_name=$(terraform workspace show)" >>  "$GITHUB_OUTPUT"

      - name: Get Workspace ID from TFC API
        id: get-workspace-id
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://app.terraform.io/api/v2/organizations/${{ env.TF_CLOUD_ORGANIZATION }}/workspaces/${{ steps.calculate-workspace-name.outputs.workspace_name }}
          method: 'GET'
          bearerToken: ${{ secrets.TF_API_TOKEN.response }}

      - name: Find PR associated with merged commit
        uses: actions/github-script@v7.0.1
        id: find-pr-number
        with:
          script: |
            github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            })

      - name: Get Runs For Workspace from TFC API
        id: get-runs-from-workspace
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://app.terraform.io/api/v2/workspaces/${{ fromJSON(steps.get-workspace-id.outputs.response).data.id }}/runs?search%5Bbasic%5D=${{ fromJSON(steps.find-pr-number.outputs.result).0.head.sha }}&filter%5Boperation%5D=save_plan&filter%5Bstatus%5D=planned_and_saved
          method: 'GET'
          bearerToken: ${{ secrets.TF_API_TOKEN.response }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.get-runs-from-workspace.outputs.response).data.0.attributes.actions.is-confirmable
        id: apply
        with:
          run: ${{ fromJSON(steps.get-runs-from-workspace.outputs.response).data.0.id }}
          comment: "Apply Run from GitHub Actions CI - ${{ steps.calculate-workspace-name.outputs.workspace_name }} - ${{ github.sha }}"